[project]
name = "schedo"
version = "0.1.0"
description = "Simple scheduler app with FastAPI and Celery"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.4.0",
    "fastapi>=0.115.10",
    "flower>=2.0.1",
    "pydantic>=2.10.6",
    "redis>=5.2.1",
    "uvicorn>=0.34.0",
]
